
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b-sync
  template:
    metadata:
      labels:
        app: service-b-sync
    spec:
      containers:
      - name: service-b-sync
        image: service_b_sync:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-sync
spec:
  type: ClusterIP
  selector:
    app: service-b-sync
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001